In [1]:
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import os
import plotly.io as pio
import pandas as pd
from pathlib import Path
from tqdm.auto import tqdm

pio.templates.default = 'plotly_white'
np.random.seed()
tqdm.pandas()

In [2]:
os.makedirs('imgs/chapter_02', exist_ok=True)
source_data = Path('../../data/london_smart_meters/')
block_data_path = source_data/'hhblock_dataset'/'hhblock_dataset'

In [3]:
assert block_data_path.is_dir()

### Converting half hourly block level dataset into a time series data

In [4]:
block_1 = pd.read_csv(block_data_path/'block_0.csv', parse_dates=False)
block_1.head()

,LCLid,day,hh_0,hh_1,hh_2,hh_3,hh_4,hh_5,hh_6,hh_7,...,hh_38,hh_39,hh_40,hh_41,hh_42,hh_43,hh_44,hh_45,hh_46,hh_47
0,MAC000002,2012-10-13,0.263,0.269,0.275,0.256,0.211,0.136,0.161,0.119,...,0.918,0.278,0.267,0.239,0.230,0.233,0.235,0.188,0.259,0.250
1,MAC000002,2012-10-14,0.262,0.166,0.226,0.088,0.126,0.082,0.123,0.083,...,1.075,0.956,0.821,0.745,0.712,0.511,0.231,0.210,0.278,0.159
2,MAC000002,2012-10-15,0.192,0.097,0.141,0.083,0.132,0.070,0.130,0.074,...,1.164,0.249,0.225,0.258,0.260,0.334,0.299,0.236,0.241,0.237
3,MAC000002,2012-10-16,0.237,0.237,0.193,0.118,0.098,0.107,0.094,0.109,...,0.966,0.172,0.192,0.228,0.203,0.211,0.188,0.213,0.157,0.202
4,MAC000002,2012-10-17,0.157,0.211,0.155,0.169,0.101,0.117,0.084,0.118,...,0.223,0.075,0.230,0.208,0.265,0.377,0.327,0.277,0.288,0.256

In [5]:
block_1['day'] = pd.to_datetime(block_1['day'], yearfirst=True)
block_1.head()

,LCLid,day,hh_0,hh_1,hh_2,hh_3,hh_4,hh_5,hh_6,hh_7,...,hh_38,hh_39,hh_40,hh_41,hh_42,hh_43,hh_44,hh_45,hh_46,hh_47
0,MAC000002,2012-10-13,0.263,0.269,0.275,0.256,0.211,0.136,0.161,0.119,...,0.918,0.278,0.267,0.239,0.230,0.233,0.235,0.188,0.259,0.250
1,MAC000002,2012-10-14,0.262,0.166,0.226,0.088,0.126,0.082,0.123,0.083,...,1.075,0.956,0.821,0.745,0.712,0.511,0.231,0.210,0.278,0.159
2,MAC000002,2012-10-15,0.192,0.097,0.141,0.083,0.132,0.070,0.130,0.074,...,1.164,0.249,0.225,0.258,0.260,0.334,0.299,0.236,0.241,0.237
3,MAC000002,2012-10-16,0.237,0.237,0.193,0.118,0.098,0.107,0.094,0.109,...,0.966,0.172,0.192,0.228,0.203,0.211,0.188,0.213,0.157,0.202
4,MAC000002,2012-10-17,0.157,0.211,0.155,0.169,0.101,0.117,0.084,0.118,...,0.223,0.075,0.230,0.208,0.265,0.377,0.327,0.277,0.288,0.256

In [6]:
block_1.groupby('LCLid')['day'].max().sample(5)

LCLid
MAC003557   2013-11-20
MAC003388   2014-02-27
MAC003668   2014-02-27
MAC005492   2014-02-27
MAC003740   2014-02-27
Name: day, dtype: datetime64[ns]

In [7]:
max_date = None

for f in tqdm(block_data_path.glob('*.csv')):
    df = pd.read_csv(f, parse_dates=False)
    df['day'] = pd.to_datetime(df['day'], yearfirst=True)
    if max_date is None:
        max_date = df['day'].max()
    else:
        if df['day'].max() > max_date:
            max_date = df['day'].max()

print(f"Max date across all blocks: {max_date}")
del df

0it [00:00, ?it/s]

Max date across all blocks: 2014-02-27 00:00:00

In [8]:
block_1.head()

,LCLid,day,hh_0,hh_1,hh_2,hh_3,hh_4,hh_5,hh_6,hh_7,...,hh_38,hh_39,hh_40,hh_41,hh_42,hh_43,hh_44,hh_45,hh_46,hh_47
0,MAC000002,2012-10-13,0.263,0.269,0.275,0.256,0.211,0.136,0.161,0.119,...,0.918,0.278,0.267,0.239,0.230,0.233,0.235,0.188,0.259,0.250
1,MAC000002,2012-10-14,0.262,0.166,0.226,0.088,0.126,0.082,0.123,0.083,...,1.075,0.956,0.821,0.745,0.712,0.511,0.231,0.210,0.278,0.159
2,MAC000002,2012-10-15,0.192,0.097,0.141,0.083,0.132,0.070,0.130,0.074,...,1.164,0.249,0.225,0.258,0.260,0.334,0.299,0.236,0.241,0.237
3,MAC000002,2012-10-16,0.237,0.237,0.193,0.118,0.098,0.107,0.094,0.109,...,0.966,0.172,0.192,0.228,0.203,0.211,0.188,0.213,0.157,0.202
4,MAC000002,2012-10-17,0.157,0.211,0.155,0.169,0.101,0.117,0.084,0.118,...,0.223,0.075,0.230,0.208,0.265,0.377,0.327,0.277,0.288,0.256

In [9]:
# Reshape the dataframe into the long form with hour blocks along the rows
block_1 = block_1.set_index(['LCLid', 'day']).stack().reset_index().rename(columns={'level_2': 'hour_block', 0: 'energy_consumption'})

# Creating a numerical hour block column
block_1['offset'] = block_1['hour_block'].str.replace('hh_', '').astype(int)

block_1.head()

       LCLid        day hour_block  energy_consumption  offset
0  MAC000002 2012-10-13       hh_0               0.263       0
1  MAC000002 2012-10-13       hh_1               0.269       1
2  MAC000002 2012-10-13       hh_2               0.275       2
3  MAC000002 2012-10-13       hh_3               0.256       3
4  MAC000002 2012-10-13       hh_4               0.211       4

### Compact Form

In [10]:
def preprocess_compact(x):
    start_date = x['day'].min()
    name = x['LCLid'].unique()[0]

    # Fill missing dates with NaN
    # Create a date range from min to max
    dr = pd.date_range(start=x['day'].min(), end=max_date, freq='1D')

    # Add hh_0 to hh_47 to columns
    dr = pd.DataFrame(columns=[f'hh_{i}' for i in range(48)], index=dr).unstack().reset_index()

    #Rename columns
    dr.columns = ['hour_block', 'day', '_']

    # Left merging the dataframes
    dr = dr.merge(x, on=['hour_block', 'day'], how='left')

    # Sort rows
    dr.sort_values(['day', 'offset'], inplace=True)

    # Extract time series array
    ts = dr['energy_consumption'].values
    len_ts = len(ts)

    return start_date, name, ts, len_ts

In [11]:
def load_process_block_compact(block_df, freq='30min', ts_identifier='series_name', value_name='series_value'):

    grps = block_df.groupby('LCLid')
    all_series = []
    all_start_dates = []
    all_names = []
    all_data = {}
    all_len = []

    for idx, df in tqdm(grps, leave=False):
        start_date, name, ts, len_ts = preprocess_compact(df)
        all_series.append(ts)
        all_start_dates.append(start_date)
        all_names.append(name)
        all_len.append(len_ts)

    all_data[ts_identifier] = all_names
    all_data['start_timestamp'] = all_start_dates
    all_data['frequency'] = freq
    all_data[value_name] = all_series
    all_data['series_length'] = all_len

    return pd.DataFrame(all_data)

In [12]:
block1_compact = load_process_block_compact(block_1, freq='30min', ts_identifier='LCLid', value_name='energy_consumption')

  0%|          | 0/50 [00:00<?, ?it/s]

In [13]:
block1_compact.head()

,LCLid,start_timestamp,frequency,energy_consumption,series_length
0,MAC000002,2012-10-13,30min,"[0.263, 0.2689999999999999, 0.275, 0.256, 0.21...",24144
1,MAC000246,2011-12-04,30min,"[0.175, 0.098, 0.144, 0.065, 0.071, 0.037, 0.0...",39216
2,MAC000450,2012-03-23,30min,"[1.337, 1.426, 0.996, 0.971, 0.994, 0.952, 0.8...",33936
3,MAC001074,2012-05-09,30min,"[0.18, 0.086, 0.106, 0.173, 0.146, 0.223, 0.21...",31680
4,MAC003223,2012-09-18,30min,"[0.076, 0.079, 0.123, 0.109, 0.051, 0.069, 0.0...",25344

In [15]:
display(block1_compact.memory_usage(deep=True))

Index                  132
LCLid                 2900
start_timestamp        400
frequency             2700
energy_consumption    6000
series_length          400
dtype: int64

Total: 0.011951446533203125

In [16]:
def preprocess_expanded(x):
    start_date = x['day'].min()

    # Create a date range from min to max
    dr = pd.date_range(start=x['day'].min(), end=x['day'].max(), freq='1D')

    # Add hh_0 to hh_47 to columns
    dr = pd.DataFrame(columns=[f'hh_{i}' for i in range(48)], index=dr).unstack().reset_index()

    # Rename columns
    dr.columns = ['hous_block', 'day', '_']

    # Merge dataframes
    dr = dr.merge(x, on=['hour_block', 'day'], how='left')
    dr['series_length'] = len(dr)

    return dr